
<<<<<<< HEAD
=======
# Generated by Django 5.0.6 on 2024-10-20 09:52

>>>>>>> b968ff37d16715d8f18b64befe5ffd79aa763712

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=100)),
                ('field2', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
